# Generated by Django 4.1.6 on 2023-02-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
