# Generated by Django 4.1.6 on 2023-02-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_city_remove_profile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
