# Generated by Django 4.1.6 on 2023-03-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_region_remove_profile_city_delete_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
