# Generated by Django 4.1.6 on 2023-03-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_region_slug_alter_region_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
