version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  redis:
    image: redis
    command: redis-server
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"

  django:
    build:
      context: .
      dockerfile: ./django.Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
